[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none';"

[[headers]]
  for = "/widget*"
  [headers.values]
    X-Frame-Options = ""
    Content-Security-Policy = "frame-ancestors *;"
